project_id = "wkrzoelctjwpiwdswmdj"

[functions.log-password-event]
verify_jwt = false

[functions.update-demo-passwords]
verify_jwt = true

[functions.generate-id-card]
verify_jwt = true

[functions.generate-id-cards-bulk]
verify_jwt = true

[functions.import-students]
verify_jwt = true

[functions.fetch-device-logs]
verify_jwt = true

[functions.auth-health-monitor]
verify_jwt = true
