project_id = "wkrzoelctjwpiwdswmdj"

[functions.log-password-event]
verify_jwt = false

[functions.update-demo-passwords]
verify_jwt = true

[functions.generate-id-card]
verify_jwt = true

[functions.generate-id-cards-bulk]
[functions.import-students]
verify_jwt = true
